export const mySkills = [
  "Semantic & accessibility HTML",
  "React-Router",
  "GitHub Pull Requests & Review",
  "CSS",
  "Redux/Toolkit",
  "Git",
  "CSS BEM convention",
  "React Hooks",
  "Teamwork",
  "CSS Grid",
  "API (fetch,axios)",
  "Scrum",
  "CSS Flexbox",
  "Promises, Async/Await",
  "Trello",
  "JavaScript ES6+",
  "Error handling",
  "Jira",
  "React.js",
  "Immutability",
  "Markdown",
  "Redux-saga",
  "NPM",
];

export const toLearnSkills = [
  "Java",
  "Node.js",
  "React Native",
  "Cypress",
  "TypeScript",
  "Sass",
  "Wordpress",
  "Node.js",
  "My SQL",
];
